export default {
  SELECT_DOMAIN: 'SELECT_DOMAIN',

  CREATE_DOMAIN: 'CREATE_DOMAIN',
  UPDATE_DOMAIN: 'UPDATE_DOMAIN',
  DELETE_DOMAIN: 'DELETE_DOMAIN',

  CREATE_TOKEN: 'CREATE_TOKEN',
  UPDATE_TOKEN: 'UPDATE_TOKEN',
  DELETE_TOKEN: 'DELETE_TOKEN',

  SET_FAVORITE_TOKEN: 'SET_FAVORITE_TOKEN',
};
